var GAME_LEVELS = [
  ["x                                                                                                           x",
   "x                                                                                                           x",
   "x                                                                                                           x",
   "x                                                                                                           x",
   "x                             o                                                                             x",
   "x                                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                             xxxxx                                                                         x",
   "x                                                                                                           x",
   "x                                                                                                           x",
   "x                                       xxxxxxxxxxxxxx                                                      x",
   "x                                                                                                           x",
   "x                 xxxxxx                                                                                    x",
   "x                                                                                                        o  x",
   "x                                                         x   x   x   x   x   x   x   x   x   x   x   xxxxxxx",
   "x                                                                                                           x",
   "x                               xxxx                                                                        x",
   "x                                                                                                           x",
   "x                                                                                                           x",
   "x                                                                                                           x",
   "x                                                                                                           x",
   "x                                          o                                                                x",
   "x                                                                                                           x",
   "x                                      xxxxxxxxxx                                                           x",
   "x                             xxx                                                                           x",
   "x                             x                                                                             x",
   "x              o              x|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
   "x                             x|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
   "x         @                   x|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                             ",
   "                                                                                                             ",
   "                                                                                                             "],
    ["x||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
     "x||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
     "x||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
     "x||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
     "x||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
     "x||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
     "x                                                                                                        x",
     "x||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||x",
     "x                                                                                                        x",
     "x                                                                                                        x",
     "x                                                              o                                         x",
     "x                                                              o                                         x",
     "x                                                              o                                         x",
     "x                                        o                     o                                         x",
     "x                                                                                                        x",
     "x                                                                                                        x",
     "x                                      o                                                                 x",
     "x                                     o                                                                  x",
     "x                 o  o  o           o                                                                    x",
     "x         @                                                                                              x",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
     "                                                                                                          ",
     "                                                                                                          "],
  ["           xx                                                                   ",
   "           xx                                                  | |              ",
   "           xx    o                   ooooo                                      ",
   "           xx                                                |     |            ",
   "           xx                                                 |||||             ",
   "           xx                                                                   ",
   "   o       xx                                                                   ",
   "   o       xx                    xxxxxxxxxxxx                                   ",
   "   o       xx                        xxxxx                                      ",
   "   o       xx                                                                   ",
   "           xx                                                                   ",
   "          xyyx                                                                  ",
   "          xyyx            xxx                              xx                   ",
   "           xx                                                                   ",
   "                                              xxx      o                        ",
   "                                    o o o                                       ",
   "                                    xxxxx             xxx                       ",
   "   y                                                                            ",
   "                                                                                ",
   "  xx                      xxxx            o o o                                 ",
   "  x                                                                             ",
   "  x            o o o                     xxxxx                                  ",
   "  x          xxxxxxxxx       o o                                    o o o       ",
   "  x  @       x       x            xx                  x                         ",
   "  xxxxxxxxxxxx       xxxxxxxxxx                                 xxxxxxxxxxxxxxxx",
   "                              x|||||||||||||||||||||||||||||||||x               ",
   "                              x|||||||||||||||||||||||||||||||||x               ",
   "                              x|||||||||||||||||||||||||||||||||x               ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "                                                                                ",
   "                                                                                "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
